name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libuv1 libuv1-dev google-perftools libgoogle-perftools-dev
    - name: Remove build artefacts
      run: make clean
    - name: Build
      run: make -j
    - uses: actions/upload-artifact@v2
      with:
        name: server
        path: build/server
        if-no-files-found: error
