name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libuv1 libuv1-dev google-perftools libgoogle-perftools-dev libleveldb-dev
    - name: Remove build artifacts
      run: make clean
    - name: Build
      run: make -j
